# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sherbert <sherbert@student.21-school.ru>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/05/07 19:44:28 by sherbert          #+#    #+#              #
#    Updated: 2020/05/07 19:55:17 by sherbert         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft.a

FLAGS	= -Wall -Werror -Wextra

INC = libft.h

SRC = \
ft_atoi.c \
ft_isascii.c \
ft_isalnum.c \
ft_isalpha.c \
ft_isdigit.c \
ft_isprint.c \
ft_tolower.c \
ft_toupper.c \
ft_strlen.c \
ft_strlcat.c \
ft_strlcpy.c \
ft_strchr.c \
ft_strrchr.c \
ft_strnstr.c \
ft_strncmp.c \
ft_memcpy.c \
ft_memmove.c \
ft_memset.c \
ft_bzero.c \
ft_memccpy.c \
ft_memchr.c \
ft_memcmp.c \
ft_calloc.c \
ft_strdup.c \
ft_itoa.c \
ft_strjoin.c \
ft_substr.c \
ft_strtrim.c \
ft_split.c \
ft_strmapi.c \
ft_putstr_fd.c \
ft_putchar_fd.c \
ft_putendl_fd.c \
ft_putnbr_fd.c \

SRC_BONUS = \
ft_lstadd_front.c \
ft_lstnew.c \
ft_lstsize.c \
ft_lstlast.c \
ft_lstadd_back.c \
ft_lstdelone.c \
ft_lstclear.c \
ft_lstiter.c \
ft_lstmap.c

SRC_DIR	= ./src/

OBJ		= $(SRC_BONUS)*.o

OBJ_DIR	= ./obj

all: $(NAME)

$(NAME): $(OBJ)

$(OBJ) : $(SRC_DIR)$(SRC)
	gcc $(FLAGS) -c $(SRC_DIR)$(SRC)
	ar rc $(NAME) $(OBJ)
	ranlib $(NAME)

bonus: $(SRC_BONUS)
	gcc $(FLAGS) -c $(SRC_DIR)$(SRC_BONUS) $(SRC_DIR)$(SRC)
	ar rc $(NAME) $(OBJ)

clean:
	/bin/rm -f $(OBJ)
	/bin/rm -f *so
	/bin/rm -rf *gch

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all

.PHONY: clean fclean all re $(NAME)
